name: google_ui
description: Google UI is Flutter open-source UI library using Material Design 2.0 with many pre-built widgets to make Flutter development easier and faster.
version: 2.1.0
homepage: https://github.com/edsulaiman/google_ui
repository: https://github.com/edsulaiman/google_ui

environment:
  sdk: '>=2.12.0 <3.0.0'
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_hooks: ^0.17.0
  intl: ^0.17.0
  spring: ^2.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true