name: google_ui
description: A collection of widgets that look similar to widgets in the Google Ads app.
version: 0.0.1
homepage: https://github.com/edsulaiman/basic_ui
repository: https://github.com/edsulaiman/basic_ui

environment:
  sdk: '>=2.12.0 <3.0.0'
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_hooks: ^0.16.0
  table_calendar: ^3.0.0
  date_format: ^2.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true